[build]
  command = "npm run build"
  functions = "netlify/functions"
  publish = "dist"

[functions]
  external_node_modules = ["express"]
  node_bundler = "esbuild"

[dev]
  command = "npm run dev"
  targetPort = 8081 # Vite ka dev port
  port = 8888         # Netlify proxy port
  publish = "dist"
  functions = "netlify/functions"

# API redirect
[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/api/:splat"
  status = 200
  force = true

# SPA fallback (React/Vue/Angular/Vite apps)
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
